name: Build and Push sprinbootDocker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t my-spring-boot-app .
          docker tag my-spring-boot-app ranjithalogesh/my-spring-boot-app:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ranjithalogesh/my-spring-boot-app:latest
