name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package
        working-directory: /home/logi/Downloads/old-files/ems-ops-phase-0/springboot-backend

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB__TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ranjithalogesh/spring-boot-image:latest ./backend  # Adjust context as needed

      - name: Push Docker image to Docker Hub
        run: |
          docker push ranjithalogesh/spring-boot-image:latest
