name: CI/CD Pipeline for Spring Boot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -U

      - name: Run Tests
        run: mvn test

      - name: Build Docker image
        run: |
          docker build -t my-spring-boot-app .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag my-spring-boot-app ${{ secrets.DOCKERHUB_USERNAME }}/my-spring-boot-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-spring-boot-app:latest
